spring : 
        datasource : 
          generate-unique-name : false
        h2 : 
            console : 
                    enabled : true
                    
        jpa :
         properties :
           javax : 
              persistence : 
                validation : 
                  mode : none  
    
# setting default page size is done in controller individually for more 
# flexibility
               
        data :
          web : 
            pageable : 
              default-page-size : 10 
              max-page-size : 100